### ISSUE TITLE
The resample data  Format Notes

### ISSUE THREAD

**Issue by ThreeIcug** [yunjunz/2021-Maduo-EQ#1]
The data in Zenodo is integral.  But the resample InSAR data format notes are not illustrated. Some examples are as follows,
Is   lon       lat           los         e          n              u         ？     ？      ？        
  98.092   34.213   -3.293   -0.764    0.113   -0.635    0.833    0.833
  99.168   34.508   82.022   -0.825    0.105   -0.556    0.832    0.832
  98.227   34.781   35.563   -0.765    0.113   -0.634    0.833    0.833
  99.306   34.416   -8.020   -0.834    0.103   -0.542    0.831    0.831
  98.581   34.488  -47.884   -0.790    0.110   -0.603    0.833    0.833
  97.971   34.554  -21.696   -0.753    0.114   -0.648    0.833    0.833
  98.738   34.201   -7.289   -0.803    0.108   -0.586    0.833    0.833
  97.735   34.607  -22.612   -0.738    0.115   -0.665    0.833    0.833

**Comment by liuwei1997** [comment]
The format is:
Longitude  Latitude  Amplitude  Vz  Vn  Ve  Weight  Weight

#(Vz, Vn, Ve) denotes the direction of Line of Sight. Two weights are identical.

**Comment by yunjunz** [comment]
Thanks @liuwei1997. It would be great if you could update the description on Zenodo for this as well.

**Comment by liuwei1997** [comment]
Updated. Thanks for the reminder @yunjunz @ThreeIcug .
